name: Train CITP Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install pandas scikit-learn transformers openpyxl mlflow torchtext pytorch-lightning torchmetrics matplotlib fasttext-wheel

    - name: ðŸ“¥ Download FastText Model
      run: |
        mkdir -p models_fasttext
        echo "DÃ©but du tÃ©lÃ©chargement du modÃ¨le FastText (4.5 Go)..."
        curl -L https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fr.300.bin.gz -o models_fasttext/cc.fr.300.bin.gz
        gunzip models_fasttext/cc.fr.300.bin.gz
        ls -lh models_fasttext/

    - name: Run Training
      run: |
        python scripts/train.py

    - name: ðŸ“¦ Upload Trained Model Assets
      if: always() # Sauvegarde mÃªme si l'entraÃ®nement est interrompu ou Ã©choue
      uses: actions/upload-artifact@v4
      with:
        name: citp-training-results
        path: |
          models/
          lightning_logs/
          mlruns/
        retention-days: 5 # Garde le fichier 5 jours pour Ã©conomiser de la place