name: Train CITP Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Installation de PyTorch version CPU (plus l√©ger pour le serveur)
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        # Installation des autres d√©pendances avec fasttext-wheel pour √©viter les erreurs de compilation
        pip install pandas scikit-learn transformers openpyxl mlflow torchtext pytorch-lightning torchmetrics matplotlib fasttext-wheel

    - name: üì• Download FastText Model
      run: |
        # Cr√©ation du dossier avec ton orthographe actuelle
        mkdir -p modelsfastext
        echo "D√©but du t√©l√©chargement du mod√®le FastText (4.5 Go)..."
        # T√©l√©chargement via curl
        curl -L https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fr.300.bin.gz -o modelsfastext/cc.fr.300.bin.gz
        echo "D√©compression du fichier..."
        gunzip modelsfastext/cc.fr.300.bin.gz
        # V√©rification finale
        echo "V√©rification du dossier :"
        ls -lh modelsfastext/

    - name: Run Training
      run: |
        # On lance le script en utilisant les fichiers t√©l√©charg√©s
        python scripts/train.py